services:
  - type: web
    name: umkm-backend
    runtime: docker
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: https://front-keuangan.vercel.app
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
